### ISSUE TITLE
Missing config value.

### ISSUE THREAD

**Issue by P4R4NORM4L** [candimods/FiveEMS_Premium#3]
**Client (production/canary) and FXServer version**  - Production fxversion FXServer 5540
**What you expected to happen** Only make 1 stretcher spawn
**What actually happens** people can spawn as many stretchers as they want, this must be restricted in the config as a value for example max 2 per player.
![image](https://user-images.githubusercontent.com/17122685/166619646-8fdbac93-7b84-494d-b80f-fbcf488aa034.png)

**Category of bug (eg. client, server, weapons, peds, native)** Script
**Reproducible steps, preferably with example script(s)** I mean just spawn the stretcher a many times as you want

**ESX or NON ESX** NON ESX

**Comment by candimods** [comment]
assigned to dev team @P4R4NORM4L will post in the discord server when update is released

**Comment by candimods** [comment]
download Version 1.9.05: released 5/14/2022 this should correct that issue @P4R4NORM4L
